apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/home-app

images:
- name: goegoe0212/home-api
  newTag: 0.1.2
- name: goegoe0212/home-temp-collector
  newTag: 0.1.1