---
apiVersion: v1
kind: Service
metadata:
  name: discord-bot-service
  namespace: home-app
spec:
  selector:
    app: discord-bot-app
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot-deployment
  namespace: home-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot-app
  template:
    metadata:
      labels:
        app: discord-bot-app
    spec:
      containers:
      - name: discord-bot-container
        image: goegoe0212/home-discord-bot
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "Asia/Tokyo"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-bot-secret
              key: DISCORD_TOKEN
        - name: DISCORD_CHANNEL_ID
          valueFrom:
            secretKeyRef:
              name: discord-bot-secret
              key: DISCORD_CHANNEL_ID
        resources:
          requests:
            cpu: "10m"
            memory: "16Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
      restartPolicy: Always
---