---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot-app
  template:
    metadata:
      labels:
        app: discord-bot-app
    spec:
      containers:
        - name: discord-bot-container
          image: goegoe0212/home-discord-bot
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: discord-bot-configmap
          - secretRef:
              name: discord-bot-secret
          resources:
            requests:
              cpu: "10m"
              memory: "16Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
      restartPolicy: Always
---