---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.20.100
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
  selector:
    app: minecraft-server
---
apiVersion: apps/v1
kind: StatefulSet  
metadata:
  name: minecraft-server
spec:
  serviceName: minecraft-server
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
        - name: minecraft-server
          image: itzg/minecraft-server
          ports:
            - containerPort: 25565
              protocol: TCP
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: "PAPER"
            - name: VERSION
              value: "1.21.8"
            - name: PAPER_CHANNEL
              value: "experimental"
            - name: PAPER_BUILD
              value: "24"
            - name: TZ
              value: "Asia/Tokyo"
            - name: MEMORY
              value: "8G"
            - name: OVERRIDE_SERVER_PROPERTIES
              value: "true"
            - name: SERVER_NAME
              value: "SSMC Minecraft Server"
            - name: MOTD
              value: "§l§b✦ Welcome to §6SSMC Minecraft Server §b✦§r"
            - name: DIFFICULTY
              value: "hard"
            - name: VIEW_DISTANCE
              value: "10"
            - name: NETWORK_COMPRESSION_THRESHOLD
              value: "256"
            - name: OPS
              value: "goegoe0212"
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "8Gi"
              cpu: "4"
          tty: true
          stdin: true
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: minecraft-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
        storageClassName: qnap-iscsi-standard
---
