---
apiVersion: v1
kind: Service
metadata:
  name: cloudflared-service
spec:
  selector:
    app: cloudflared
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
data:
  config.yaml: |
    ingress:
      - hostname: metabase.goegoe0212.com
        service: http://metabase-service.metabase
      - hostname: argocd.goegoe0212.com
        service: http://argocd-server.argocd:8080
      - hostname: immich.goegoe0212.com
        service: http://immich-server-service.immich:2283
      - service: http_status:404
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared
        imagePullPolicy: Always
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared/
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflared-secret
              key: token
        args:
          - tunnel
          - --config
          - /etc/cloudflared/config.yaml
          - run
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
      volumes:
      - name: config
        configMap:
          name: cloudflared-config
---