---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-bot-secret
  namespace: discord-bot
spec:
  encryptedData:
    DISCORD_CHANNEL_ID: AgBYQgQcy8t+Um2JenI7lfRAscC2AP7qvLXbR9wuCpHjs5b8uhXQp+GApRetjHOt43udTGK7x5lI3mIYXKJUrkTufRVYh8oWTtd7EwsvbNvLN/OxA1JJ1pTqQWrQ53vzyPuyXcDGgJRCEIvhUkUjYMn50i6h60D1f2+nkDmDXVJiEgkIn9v7YUQeTowvg0FJGj0DFhpe+koKehWfEoiol5b6KTEVEFLfdYTadWQniJiO8OtLABFt6q6M1YTCb1xt+6qgFRcvw2tHcZ2UN/SF8za0g/aVCR7NPtchk2zDpjbdm+0ExbrkH/RUV9QDt3if9DUzoy/uVHib2JZPqPXaOo1I9g9IH+FiXfrz5yMWMwNPC560azR/NE78FyzU9ytdmD/kWIDtsmMbEcOfkF8XItByvoa5BB8up3IaW2loJlhEPiuOPG/Gja5puGBVmUojdycmMu3EEUxIz/iQchHzC9242cx3fvFYGtJ6BPz1CI3TBdMEkD/gWcr2SpNW1SL+Y7W9SmcVxSkqFd5NOGaxLtqjlnA1yQdKYcU9IAcCKGNm6ZsbKtomz8JaCDZj2eWyAh9jkN/pGBJCkwwJtOjkhrQkyFPh6u1pn3WtqQ97r46WoKV7a9Kg88DWTjcgRFeucbnoDc8dlyWf6t3x93hW807eqLJZLFXgw3GXB2M9m67ZPqkCE2z0UXJXxpo/ONbVjOP2YDeQTZsTjXpcfnaH6IpkBTeu
    DISCORD_TOKEN: AgCQs5sQq7zqkGohzdZxRDNqFJS2Vm4aXkrNbBrRvOsg38Qp+5GJAZRuFd5NfbjUlDKC0zsuaRNmQeKmH2vezPCkelR59TVVpGVHlEzDTlqYHbrFHRWZpq9ZDlqNeGmOKQOZBL6oxdvcV0k/jApz0c3OfH64xl8cni04hPBWzlVfrSL3tXr02RRHTMRkmqFArXLAKPf+bKG8gu6lF7Z0mFjLmmNgYJblngIxSoC45XYA1hJVFgkrmtseEShUY67D/l5iPk7UfEbwutt2zr5Iwe26j0BE5Bh8zyUUGimy4DlsZnTsr+x7Z202EUK2UHOOw3uc7H2pDx29E6pAmm4WzCeH3se6xqCEFxYXzMGq/DFLidPJ/DOGdgdDQVnHu9J4KiwTsS0qCtcV4WdwcxpH2rmRgJ4fkxypJjknWhz9zjJZbnvrjPTaGYNvFfbKjBtSVNChZb185G/dwfMYXnVR/TVGqjRASzmK9zGArUlTwrB2qRfGbKF0gUEianVGIutcAVnqfRckWREx9Frir0ByqR4qwi876tJQt8f9SPmuVsY8JPLwsQ3kxfPIAMrTKkox7JCmdQ6afaKEvxjJEhJalbhZPbD6T7MvGjFDWlZ0E+qTghSn8QoGoN3AiKShpqjSRcsijl9x8HobR2DbNWqpAr9XoHXK2pAG/1sL8cQ36u0P6nExi2bbZf6TvMtAU5jp7OXPqEbMzcSsVBW6oF16qw/mb4wtkLPwaWCTwDrLtYVvLsqEm+c9na8xaN8kCInbbtJdGCc7sB1cDaSVIZmrPvSA6Azf0uMyJCE=
  template:
    metadata:
      name: discord-bot-secret
      namespace: discord-bot
    type: Opaque
