---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: qnap-iscsi-standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: qnap-iscsi-standard
---