---
apiVersion: v1
kind: Service
metadata:
  name: samba-service
  namespace: samba
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.20.106
  ports:
    - name: smb
      port: 445
      targetPort: 445
      protocol: TCP
  selector:
    app: samba-server
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: samba-nfs-pv
spec:
  capacity:
    storage: 350Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.20.20
    path: /home/cloudinit/data/plex/data
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-nfs-pvc
  namespace: samba
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 350Gi
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba-server
  namespace: samba
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: samba-server
  template:
    metadata:
      labels:
        app: samba-server
    spec:
      containers:
        - name: samba-server
          image: goegoe0212/home-samba:latest
          ports:
            - containerPort: 445
              protocol: TCP
          env:
            - name: TZ
              value: "Asia/Tokyo"
            - name: SAMBA_USER
              value: "root"
            - name: SAMBA_PW
              value: "Password"
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: data
              mountPath: /data
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: samba-nfs-pvc
---
