apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/argocd-install
- ../../base/metallb
- ../../base/longhorn
- ../../base/nginx-ingress
- ../../base/argocd-applications
