---
apiVersion: v1
kind: Service
metadata:
  name: cloudflared-service
  namespace: home-app
spec:
  selector:
    app: cloudflared
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: home-app
data:
  config.yaml: |
    ingress:
      - hostname: metabase.ssmcgames.com
        service: http://metabase-service.home-app
      - hostname: argocd.ssmcgames.com
        service: http://argocd-server.argocd:8080
      - service: http_status:404
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: home-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared/
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflared-secret
              key: token
        args:
          - tunnel
          - --config
          - /etc/cloudflared/config.yaml
          - run
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
      volumes:
      - name: config
        configMap:
          name: cloudflared-config
---