apiVersion: v1
kind: Service
metadata:
  name: metabase-service
  namespace: home-app
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.20.103
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: metabase-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase-app
  namespace: home-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase-app
  template:
    metadata:
      labels:
        app: metabase-app
    spec:
      containers:
        - name: metabase
          image: metabase/metabase:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: TZ
              value: "Asia/Tokyo"
            - name: JAVA_OPTS
              value: "-Xmx2g"
            - name: MB_DB_TYPE
              value: "postgres"
            - name: MB_DB_DBNAME
              value: "postgresdb"
            - name: MB_DB_PORT
              value: "5432"
            - name: MB_DB_USER
              value: "admin"
            - name: MB_DB_PASS
              value: "Passw0rd"
            - name: MB_DB_HOST
              value: "postgres-service"
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "2Gi"
      restartPolicy: Always
---