---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  namespace: minecraft
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.20.100
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
  selector:
    app: minecraft-server
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-nfs-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.20.20
    path: /home/cloudinit/data/minecraft
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-nfs-pvc
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  namespace: minecraft
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
        - name: minecraft-server
          image: itzg/minecraft-server
          ports:
            - containerPort: 25565
              protocol: TCP
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: "PAPER"
            - name: VERSION
              value: "1.21.4"
            - name: TZ
              value: "Asia/Tokyo"
            - name: MEMORY
              value: "8G"
            - name: SERVER_NAME
              value: "minecraft server"
            - name: MOTD
              value: "Welcome! minecraft server!!"
            - name: DIFFICULTY
              value: "hard"
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "8Gi"
              cpu: "4"
          tty: true
          stdin: true
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
      restartPolicy: Always
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-nfs-pvc
---
