---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: home-app
spec:
  selector:
    app: postgres-app
  type: LoadBalancer
  loadBalancerIP: 192.168.20.102
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-nfs-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.20.20
    path: /home/cloudinit/data/postgresql
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-app
  namespace: home-app
spec:
  serviceName: "postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-app
  template:
    metadata:
      labels:
        app: postgres-app
    spec:
      containers:
        - name: postgres-app
          image: timescale/timescaledb:latest-pg17
          ports:
            - containerPort: 5432
          env:
            - name: TZ
              value: "Asia/Tokyo"
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "Passw0rd"
            - name: POSTGRES_DB
              value: "postgresdb"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 20Gi
        storageClassName: ""
---