---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: home-temp-collector-secret
  namespace: temp-collector
spec:
  encryptedData:
    NATURE_API_KEY: AgC92yI9KXLQHr2/eoFnllLLGGfgFgmx+x6DvpOlBqjj5XMXAZD6buo3GyRmuiIzgKrzvKLFCjm28SEdUi4D1A8/fYabZ8sSANuqz8UKHsMlPdHVwKUfzJcVQhQ7jaQcn1ZHICJYRV2N9rnQFs8oHVJ+N0GzAAcO6/37LE+C7SV7t+ViZXq8nzWZotfewSZEPzuBICouUodYYfkdclc7MaJE7vXqmkSD7MksqOp5UZ16rmQ3Z+69Pfi33peT54wFbnGUKhWtmSImakUDaQvaIzTAb/ufCO3IehP9kUhV7Dzicaf5CzoBtPjKbuDx3oAViMgCWeNshXTgUHx5WlrbUOKfa5Pn53oW6z7PEm5h7flbaWA835pqa35ss49Ms3Xs6WNRQ1dfG0NnZQqv+zR1r63fUGKj1TRSNNE1UeVv2uHeBVpj/zl+YERUDDx9Vk8wDMv0hU8p+c/ICQFTa8oh+QZROltJmWZsPfr7Qteu9HTJFBrAe1vCjiFUTuuLIv9SpMCNJBmHIHHsqCGZUXf0FzfKBCsPQ1HUCgzrb8i2SXbhPODCcctfRfmayzvWgNr0AxG+KpMAgPVBRoUXUsBu0r79ngWS409pHR4tk9twGWZDN0SZieODzr659QznuIJfCbqlXkHGZbDqgJcuGWwK8pN+QCGxOypA61SZ+gR6sA1c07m1Vvcz1gh4oU2RGqMG/5p8aKah0POQ7oYXotkTNj13gu7yPSnnU5DWJRw/Wra0iDoKPgoaqq3xpKEM4Iegp6hwOxDud9RySvTds/iFqb+OYTXg5c4FLNWSBzOURddHEhGvMqRBBUcLLK3s4mFa
  template:
    metadata:
      name: home-temp-collector-secret
      namespace: temp-collector
    type: Opaque
