---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-secret
  namespace: cloudflare
spec:
  encryptedData:
    token: AgCYjLbKOhzlAfFQVpNqpb3DIQ4A5kSeC9pYlnWhdliR6gXz7H0g/DYM4R62dUXZM3fKnBvWp7bEUjRwLNqLgz27WUgV137dc3Cg/4BJ7TvWmIe+yq+l3w3csL5d31YlChcvrYXM8J1U4vxc8smPy/edideHiHFGH8Ju/qKUjgI4IGN/jtvLI7/Ahx5KCJxd+Ut7p5VnbP9Ha6DzkFYL4x5T3wRGppFJ4CbuedBYbDeIKBarGMkAOAhoDZgh45dpzMj0ItEzijDwwpOvFwXk6EBM+8sHbE9s9LELZjrsnLocg+i7KE/ncNIq+uYR2U99pbA4nn7UM8zUCfb5MeyaWmcLZwrsEXjG08RKFEQ5LrASYaQNIs20NZ4l2Cme0ukD4lfmy3unT/oRnnBlQ0Qup5gQ1BiO7b+vABOEteprfSnZBy6fzVWVDfWRqsav5cHO5eW9dfS9pwgIYQL1HhZznMEgW4IlHZhswUhGSpN+yiTTHHn4MCqRDhozaR/p7XXp/JNuogJU9pBnSvkv1dtV4KPsYoiz0MXQkBYP+8Xg2z0mwZcFzk1UUgWQZLnjVDBJDt93Yhd41T5XKpsorJlTEbMtE6vPcWJTOad3U3hU70eIPJ3Ensi03DfnqcWCWAYlZ454m1WMZ3X98BKxsmaRbu/ZsGj4CexgtoXvlnd4yY31gPR153uwFpB1PFmdSnf6kcLAxUltvkP0iGdneK+iCo3UxBz3y/SKIVXFBQKyQVZECYlwQFDk6kK0+m1r6cEtFVFGEKilkAoX+8p8I6EGynkDoXKVxyZV2Pfy1A5Rjmlq5h7q4N/P/P4allvyPMldblDMFFZiUhMtBw3mhFckU+u76665+AnYnMhLlOshtMG3knix14BSL0yjC2znetvK5KpPFVva5jrxfH75eEok49H/9kAZa34/cxlTCSkLK/q+Hvemmvq/Tbdp
  template:
    metadata:
      name: cloudflared-secret
      namespace: cloudflare
    type: Opaque
