---
apiVersion: v1
kind: Service
metadata:
  name: immich-server-service
  labels:
    app: immich-server
spec:
  selector:
    app: immich-server
  ports:
    - port: 2283
      targetPort: 2283
---
apiVersion: v1
kind: Service
metadata:
  name: immich-server-lb
spec:
  selector:
    app: immich-server
  type: LoadBalancer
  loadBalancerIP: 192.168.20.103
  ports:
    - name: http
      port: 80
      targetPort: 2283
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server-deployment
  labels:
    app: immich-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-server
  template:
    metadata:
      labels:
        app: immich-server
    spec:
      containers:
        - name: server
          image: ghcr.io/immich-app/immich-server
          ports:
            - containerPort: 2283
          env:
            - name: TZ
              value: "Asia/Tokyo"
            # Postgres
            - name: DB_HOSTNAME
              value: database-service
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_DATABASE_NAME
              value: immich
            - name: DB_VECTOR_EXTENSION
              value: "pgvecto.rs"

            # Redis
            - name: REDIS_HOSTNAME
              value: redis-service
            - name: REDIS_PORT
              value: "6379"

            # その他
            - name: IMMICH_PORT
              value: "2283"
            - name: NODE_ENV
              value: "production"

          volumeMounts:
            - name: immich-library-data
              mountPath: /data
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "4Gi"
      volumes:
        - name: immich-library-data
          persistentVolumeClaim:
            claimName: immich-library-data
---