namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

patches:
- path: argocd-cmd-params-cm-patch.yaml
  target:
    group: "" 
    version: v1
    kind: ConfigMap
    name: argocd-cmd-params-cm
    namespace: argocd